version: '3.1'

services:
  db:
    image: postgres
    container_name: booking-db
    volumes:
      - ./containers/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=booking
      - POSTGRES_PASSWORD=password
  
  adminer:
    image: adminer
    container_name: booking-adminer
    ports:
      - 5656:8080

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://188.166.182.27:8080
        - REACT_APP_SOCKET_URL=http://188.166.182.27:4000
    image: booking-frontend
    container_name: booking-frontend
    ports:
      - 3000:3000
  
  apiserver:
    build:
      context: apiServer
      dockerfile: Dockerfile
    image: booking-api
    container_name: booking-api
    environment:
      - WS_API_URL=http://wsserver:4000
      - DB_USER=booking
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_DATABASE=booking
    links:
      - db
      - wsserver
    ports:
      - 8080:8080
  
  wsserver:
    build:
      context: wsServer
      dockerfile: Dockerfile
    image: booking-ws
    container_name: booking-ws
    ports:
      - 4000:4000
