version: '3.1'

services:
  traefik:
    image: traefik
    container_name: traefik
    command: --configFile=/var/traefik/traefik.toml
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/var/traefik/traefik.toml
    networks:
      - web
      - internal
    labels:
      - traefik.backend=traefik

  db:
    image: postgres
    container_name: booking-db
    volumes:
      - ./containers/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=booking
      - POSTGRES_PASSWORD=password
    networks:
      - internal
    labels:
      - traefik.enable=false
  
  adminer:
    image: adminer
    container_name: booking-adminer
    networks:
      - web
      - internal
    labels:
      - traefik.backend=adminer
      - traefik.frontend.rule=PathPrefix:/db-manager
      - traefik.docker.network=web
      - traefik.port=8080
    depends_on:
      - db

  frontend:
    image: booking-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
        - REACT_APP_SOCKET_URL=
    container_name: booking-frontend
    networks:
      - web
      - internal
    labels:
      - traefik.backend=webui
      - traefik.frontend.rule=PathPrefix:/
      - traefik.docker.network=web
      - traefik.port=3000
    depends_on:
      - apiserver
      - wsserver
  
  apiserver:
    image: booking-api
    build:
      context: apiServer
      dockerfile: Dockerfile
    container_name: booking-api
    environment:
      - WS_API_URL=http://wsserver:4000
      - DB_USER=booking
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_DATABASE=booking
    depends_on:
      - db
      - wsserver
    networks:
      - web
      - internal
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=PathPrefixStrip:/api
      - traefik.docker.network=web
      - traefik.port=8080
  
  wsserver:
    image: booking-ws
    build:
      context: wsServer
      dockerfile: Dockerfile
    container_name: booking-ws
    networks:
      - web
      - internal
    labels:
      - traefik.backend=ws
      - traefik.frontend.rule=PathPrefix:/subscribe
      - traefik.docker.network=web
      - traefik.port=4000

networks:
  web:
  internal: